import { v4 as uuidv4 } from 'uuid';

export const initialList = {
  lists: [
    {
      name: 'Shopping list',
      id: uuidv4(),
      categories: [
        {
          name: 'Fruit and vegetables',
          id: uuidv4(),
          items: [
            {
              name: 'Avocado',
              note: '',
              image: '',
              quantity: 0,
              id: uuidv4(),
            },
            {
              name: 'Banana',
              note: '',
              image: '',
              quantity: 0,
              id: uuidv4(),
            },
            {
              name: 'Bunch of carrots 5pcs',
              note: '',
              image: '',
              quantity: 0,
              id: uuidv4(),
            },
            {
              name: 'Chicken 1kg',
              note: '',
              image: '',
              quantity: 0,
              id: uuidv4(),
            },
            {
              name: 'Pre-cooked corn 450g',
              note: '',
              image: '',
              quantity: 0,
              id: uuidv4(),
            },
            {
              name: 'Mandarin Nadorcott',
              note: '',
              image: '',
              quantity: 0,
              id: uuidv4(),
            },
            {
              name: 'Piele De Sapo Melon',
              note: '',
              image: '',
              quantity: 0,
              id: uuidv4(),
            },
            {
              name: 'Watermelon',
              note: '',
              image: '',
              quantity: 0,
              id: uuidv4(),
            },
          ],
        },
        {
          name: 'Meat and Fish',
          id: uuidv4(),
          items: [
            {
              name: 'Chicken leg box',
              note: '',
              image: '',
              quantity: 0,
              id: uuidv4(),
            },
            {
              name: 'Chicken 1kg',
              note: '',
              image: '',
              quantity: 0,
              id: uuidv4(),
            },
            {
              name: 'Pork fillets 450g',
              note: '',
              image: '',
              quantity: 0,
              id: uuidv4(),
            },
            {
              name: 'Salmon 1kg',
              note: '',
              image: '',
              quantity: 0,
              id: uuidv4(),
            },
          ],
        },
        {
          name: 'Beverages',
          note: '',
          image: '',
          quantity: 0,
          id: uuidv4(),
          items: [
            {
              name: 'Avocado',
              note: '',
              image: '',
              quantity: 0,
              id: uuidv4(),
            },
            {
              name: 'Banana',
              note: '',
              image: '',
              quantity: 0,
              id: uuidv4(),
            },
            {
              name: 'Bunch of carrots 5pcs',
              note: '',
              image: '',
              quantity: 0,
              id: uuidv4(),
            },
            {
              name: 'Chicken 1kg',
              note: '',
              image: '',
              quantity: 0,
              id: uuidv4(),
            },
            {
              name: 'Pre-cooked corn 450g',
              note: '',
              image: '',
              quantity: 0,
              id: uuidv4(),
            },
            {
              name: 'Mandarin Nadorcott',
              note: '',
              image: '',
              quantity: 0,
              id: uuidv4(),
            },
            {
              name: 'Piele De Sapo Melon',
              note: '',
              image: '',
              quantity: 0,
              id: uuidv4(),
            },
            {
              name: 'Watermelon',
              note: '',
              image: '',
              quantity: 0,
              id: uuidv4(),
            },
          ],
        },
        {
          name: 'Pets',
          note: '',
          image: '',
          quantity: 0,
          id: uuidv4(),
          items: [
            {
              name: 'Chicken leg box',
              note: '',
              image: '',
              quantity: 0,
              id: uuidv4(),
            },
            {
              name: 'Chicken 1kg',
              note: '',
              image: '',
              quantity: 0,
              id: uuidv4(),
            },
            {
              name: 'Pork fillets 450g',
              note: '',
              image: '',
              quantity: 0,
              id: uuidv4(),
            },
            {
              name: 'Salmon 1kg',
              note: '',
              image: '',
              quantity: 0,
              id: uuidv4(),
            },
          ],
        },
      ],
    },
  ],
};
